import { Request, Response } from 'express';
import { prisma, useRealDb, memoryDb } from '../lib/db';
import { emitRoomUpdate, emitNewLead } from '../services/socketService';
import { sendMail, sendSMS } from '../utils/notifications';

// 1. Create Lead (Triggered during multi-step checkout form flow)
export const createLead = async (req: Request, res: Response): Promise<void> => {
  try {
    const { fullName, email, phone, preferredCategory, selectedRoomNumber, selectedBedNumber, bookingProgress } = req.body;

    if (!fullName || !email || !phone || !preferredCategory) {
      res.status(400).json({ message: 'Missing required lead parameters' });
      return;
    }

    const leadId = `LID-${Math.floor(100000 + Math.random() * 900000)}`;

    if (useRealDb && prisma) {
      // Find if lead already exists by email
      let lead = await prisma.supportLead.findFirst({
        where: { email }
      });

      if (lead) {
        lead = await prisma.supportLead.update({
          where: { id: lead.id },
          data: {
            fullName,
            phone,
            preferredCategory,
            selectedRoomNumber,
            selectedBedNumber,
            bookingProgress,
            updatedAt: new Date()
          }
        });
      } else {
        lead = await prisma.supportLead.create({
          data: {
            leadId,
            fullName,
            email,
            phone,
            preferredCategory,
            selectedRoomNumber,
            selectedBedNumber,
            bookingProgress,
            status: 'NEW_INQUIRY',
            notes: ['Lead automatically captured by Checkout Form']
          }
        });
      }

      // Notify Support Dashboard & Send Mock email
      emitNewLead(lead);
      await sendMail(email, 'Booking Inquiry Created - HMR Hostel', `Hi ${fullName}, thank you for starting your booking. Complete your fee payment to secure your bed!`);
      await sendMail('support@hmr.com', 'New Booking Inquiry Alert', `A new inquiry was generated by student ${fullName} (${phone}) for a ${preferredCategory}.`);

      res.status(200).json(lead);
    } else {
      // Memory DB
      let lead = memoryDb.supportLeads.find(l => l.email.toLowerCase() === email.toLowerCase());

      if (lead) {
        lead.fullName = fullName;
        lead.phone = phone;
        lead.preferredCategory = preferredCategory;
        lead.selectedRoomNumber = selectedRoomNumber;
        lead.selectedBedNumber = selectedBedNumber;
        lead.bookingProgress = bookingProgress;
        lead.updatedAt = new Date();
      } else {
        lead = {
          id: `lead_${Date.now()}`,
          leadId,
          fullName,
          email,
          phone,
          preferredCategory,
          selectedRoomNumber,
          selectedBedNumber,
          bookingProgress,
          status: 'NEW_INQUIRY',
          notes: ['Lead automatically captured by Checkout Form'],
          createdAt: new Date(),
          updatedAt: new Date()
        };
        memoryDb.supportLeads.push(lead);
      }

      emitNewLead(lead);
      await sendMail(email, 'Booking Inquiry Created - HMR Hostel', `Hi ${fullName}, thank you for starting your booking. Complete your fee payment to secure your bed!`);
      await sendMail('support@hmr.com', 'New Booking Inquiry Alert', `A new inquiry was generated by student ${fullName} (${phone}) for a ${preferredCategory}.`);

      res.status(200).json(lead);
    }
  } catch (error: any) {
    res.status(500).json({ message: 'Error capturing lead', error: error.message });
  }
};

// 2. Complete Booking & Mock Payment Confirmation
export const confirmBooking = async (req: Request, res: Response): Promise<void> => {
  try {
    const userId = (req as any).user?.id;
    const {
      roomId, bedNumber, fullName, fatherName, motherName, gender, dob, phone, emergencyContact,
      collegeName, course, year, studentId, aadharNumber, permanentAddress, currentAddress,
      guardianName, guardianPhone, guardianRelation, bloodGroup, medicalHistory,
      photoUrl, aadharUrl, collegeIdUrl, signatureUrl, paymentMethod, amountPaid
    } = req.body;

    if (!roomId || !bedNumber || !fullName || !aadharNumber) {
      res.status(400).json({ message: 'Missing booking details' });
      return;
    }

    const transactionId = `TXN-${Math.floor(100000000 + Math.random() * 900000000)}`;
    const bookingId = `BKG-${Math.floor(100000 + Math.random() * 900000)}`;
    const qrPayload = JSON.stringify({ bookingId, fullName, roomId, bedNumber, amountPaid });

    if (useRealDb && prisma) {
      // Find the student
      const user = await prisma.user.findUnique({
        where: { id: userId },
        include: { studentProfile: true }
      });
      if (!user || !user.studentProfile) {
        res.status(404).json({ message: 'Student profile not found' });
        return;
      }
      
      const studentIdDb = user.studentProfile.id;

      // Update student profile with full details
      const updatedStudent = await prisma.student.update({
        where: { id: studentIdDb },
        data: {
          fatherName, motherName, gender, dob: dob ? new Date(dob) : null,
          phone, emergencyContact, collegeName, course, year, studentId,
          aadharNumber, permanentAddress, currentAddress, guardianName,
          guardianPhone, guardianRelation, bloodGroup, medicalHistory,
          photoUrl, aadharUrl, collegeIdUrl, signatureUrl,
          roomId, bedNumber
        }
      });

      // Create Booking record
      const booking = await prisma.booking.create({
        data: {
          bookingId,
          studentId: studentIdDb,
          roomId,
          bedNumber,
          status: 'APPROVED', // Complete booking flow defaults to approved upon payment
          fullName,
          phone,
          email: user.email,
          collegeName: collegeName || '',
          course: course || '',
          year: year || '',
          aadharNumber,
          paymentStatus: 'PAID',
          paymentId: transactionId,
          qrCode: qrPayload
        }
      });

      // Create Payment entry
      await prisma.payment.create({
        data: {
          transactionId,
          studentId: studentIdDb,
          amount: Number(amountPaid),
          method: paymentMethod || 'RAZORPAY_UPI',
          status: 'SUCCESS'
        }
      });

      // Fetch Room details to emit socket update
      const room = await prisma.room.findUnique({
        where: { id: roomId },
        include: { students: true }
      });
      if (room) {
        const occupancy = room.students.length;
        let roomStatus: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED' | 'MAINTENANCE' = 'AVAILABLE';
        if (occupancy >= room.capacity) roomStatus = 'OCCUPIED';
        emitRoomUpdate(roomId, room.roomNumber, roomStatus, occupancy, room.capacity);
      }

      // Send confirmation notices
      await sendMail(user.email, 'Booking Confirmed - HMR Hostel', `Hello ${fullName}, your booking ${bookingId} has been confirmed. Welcome to Room ${room?.roomNumber || roomId}!`);
      await sendSMS(phone, `Booking confirmed at HMR Hostel! Room: ${room?.roomNumber || ''}, Bed: ${bedNumber}. Log in to view your Digital ID card.`);

      // Update matching leads to "CLOSED"
      await prisma.supportLead.updateMany({
        where: { email: user.email },
        data: { status: 'CLOSED', bookingProgress: 'Completed' }
      });

      res.status(200).json({ success: true, booking, transactionId });
    } else {
      // Memory DB fallback
      const studentIdx = memoryDb.students.findIndex(s => s.userId === userId);
      if (studentIdx === -1) {
        res.status(404).json({ message: 'Student profile not found' });
        return;
      }

      const student = memoryDb.students[studentIdx];
      const room = memoryDb.rooms.find(r => r.id === roomId);
      if (!room) {
        res.status(404).json({ message: 'Room not found' });
        return;
      }

      // Update student profile
      memoryDb.students[studentIdx] = {
        ...student,
        fatherName, motherName, gender, dob: dob ? new Date(dob) : null,
        phone, emergencyContact, collegeName, course, year, studentId,
        aadharNumber, permanentAddress, currentAddress, guardianName,
        guardianPhone, guardianRelation, bloodGroup, medicalHistory,
        photoUrl, aadharUrl, collegeIdUrl, signatureUrl,
        roomId, bedNumber
      };

      const studentUser = memoryDb.users.find(u => u.id === student.userId);
      const studentEmail = studentUser?.email || '';

      // Create booking
      const newBooking = {
        id: `booking_${Date.now()}`,
        bookingId,
        studentId: student.id,
        roomId,
        bedNumber,
        status: 'APPROVED' as const,
        fullName,
        phone,
        email: studentEmail,
        collegeName: collegeName || '',
        course: course || '',
        year: year || '',
        aadharNumber,
        paymentStatus: 'PAID' as const,
        paymentId: transactionId,
        qrCode: qrPayload,
        createdAt: new Date(),
        updatedAt: new Date()
      };
      memoryDb.bookings.push(newBooking);

      // Create Payment entry
      memoryDb.payments.push({
        id: `pay_${Date.now()}`,
        transactionId,
        studentId: student.id,
        amount: Number(amountPaid),
        method: paymentMethod || 'RAZORPAY_UPI',
        status: 'SUCCESS',
        createdAt: new Date()
      });

      // Calculate room occupancy
      const roomOccupancy = memoryDb.students.filter(s => s.roomId === roomId).length;
      let roomStatus: 'AVAILABLE' | 'OCCUPIED' | 'RESERVED' | 'MAINTENANCE' = 'AVAILABLE';
      if (roomOccupancy >= room.capacity) roomStatus = 'OCCUPIED';
      
      emitRoomUpdate(roomId, room.roomNumber, roomStatus, roomOccupancy, room.capacity);

      // Send mock alerts
      await sendMail(studentEmail, 'Booking Confirmed - HMR Hostel', `Hello ${fullName}, your booking ${bookingId} has been confirmed. Welcome to Room ${room.roomNumber}!`);
      await sendSMS(phone, `Booking confirmed at HMR Hostel! Room: ${room.roomNumber}, Bed: ${bedNumber}. Log in to view your Digital ID card.`);

      // Update leads status
      const lead = memoryDb.supportLeads.find(l => l.email.toLowerCase() === studentEmail.toLowerCase());
      if (lead) {
        lead.status = 'CLOSED';
        lead.bookingProgress = 'Completed';
      }

      res.status(200).json({ success: true, booking: newBooking, transactionId });
    }
  } catch (error: any) {
    console.error('Booking confirmation failed:', error);
    res.status(500).json({ message: 'Error processing booking', error: error.message });
  }
};

// 3. Get all leads (Admin Dashboard)
export const getLeads = async (req: Request, res: Response): Promise<void> => {
  try {
    if (useRealDb && prisma) {
      const leads = await prisma.supportLead.findMany({
        orderBy: { createdAt: 'desc' }
      });
      res.status(200).json(leads);
    } else {
      // Memory DB
      res.status(200).json(memoryDb.supportLeads.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()));
    }
  } catch (error: any) {
    res.status(500).json({ message: 'Error fetching support leads', error: error.message });
  }
};

// 4. Update Lead Status / Assigned executive
export const updateLead = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const { status, assignedTo, notes } = req.body;

    if (useRealDb && prisma) {
      const updatedLead = await prisma.supportLead.update({
        where: { id },
        data: {
          status,
          assignedTo,
          notes: notes ? { push: notes } : undefined
        }
      });
      res.status(200).json(updatedLead);
    } else {
      // Memory DB
      const leadIdx = memoryDb.supportLeads.findIndex(l => l.id === id);
      if (leadIdx === -1) {
        res.status(404).json({ message: 'Lead not found' });
        return;
      }

      const lead = memoryDb.supportLeads[leadIdx];
      memoryDb.supportLeads[leadIdx] = {
        ...lead,
        status: status || lead.status,
        assignedTo: assignedTo !== undefined ? assignedTo : lead.assignedTo,
        notes: notes ? [...lead.notes, notes] : lead.notes
      };

      res.status(200).json(memoryDb.supportLeads[leadIdx]);
    }
  } catch (error: any) {
    res.status(500).json({ message: 'Error updating lead', error: error.message });
  }
};

// 5. Get all bookings
export const getBookings = async (req: Request, res: Response): Promise<void> => {
  try {
    if (useRealDb && prisma) {
      const bookings = await prisma.booking.findMany({
        include: { room: true, student: true },
        orderBy: { createdAt: 'desc' }
      });
      res.status(200).json(bookings);
    } else {
      // Memory DB
      const bookings = memoryDb.bookings.map(b => {
        const student = memoryDb.students.find(s => s.id === b.studentId);
        const room = memoryDb.rooms.find(r => r.id === b.roomId);
        return {
          ...b,
          student,
          room
        };
      }).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
      
      res.status(200).json(bookings);
    }
  } catch (error: any) {
    res.status(500).json({ message: 'Error fetching bookings', error: error.message });
  }
};
export default confirmBooking;
